# Example configuration YAML

# The server dir is the folder that contains server.properties
server_dir: /path/to/serverfolder
# The output dir is where you want the JSON files to get saved/updated
# output_dir: /srv/minecraft-api

# Use cache dir to specify an alternate (or determinitstic) location for
# mcdata-to-json to store temporary files and extracted data from the
# minecraft jar file.
# cache_dir: /opt/mcdata-to-json
